-- CREATE SEQUENCE hibernate_sequence;
CREATE TABLE weather (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    temperature FLOAT,
    created_date timestamp NULL,
    modified_date timestamp NULL
);

